title: Binary Ch01ce (blog)
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal blog. I sometimes post about Open Source, coding, Mozilla, and some of my various views or passions.
baseurl: "" # the subpath of your site, e.g. /blog
index_path: "/blog/"
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ValentinGosu
github_username:  valenting
mastodon:
- username: valenting
  instance: mastodon.social

# Build settings
markdown: kramdown
remote_theme: jekyll/minima

minima:
  skin: dark

# paginate:     20

plugins:
  - jekyll-feed

permalink:  /blog/:year/:month/:title
